name: ghci-dap
version: '0.0.27.0'
synopsis: ghci-dap is a GHCi having DAP interface.
description: Please see README.md
category: Development
author: phoityne_hs
maintainer: phoityne.hs@gmail.com
copyright: 2017-2025 phoityne_hs
license: BSD3
homepage: https://github.com/phoityne/ghci-dap
bug-reports: https://github.com/phoityne/ghci-dap/issues
extra-source-files:
- README.md
- Changelog.md

when:
- condition: impl(ghc < 8.10.0)
  dependencies: unsupported-ghc-version > 1 && < 1

dependencies:
- base >=4.7 && <5
- ghc
- ghci
- ghc-paths
- ghc-prim
- transformers
- containers
- time
- directory
- haskeline
- array
- process
- ghc-boot
- filepath
- bytestring
- deepseq
- text
- exceptions
- haskell-dap >= 0.0.15.0

library:
  source-dirs: src
  exposed-modules:
  - GHCi.DAP

executables:
  ghci-dap:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fno-warn-unused-do-bind
    - -fno-warn-name-shadowing
    cc-options: -fPIC
    cpp-options: -DGHCI -DHAVE_INTERNAL_INTERPRETER -DGHC_LOADED_INTO_GHCI
    dependencies:
    - ghci-dap

    when:
    - condition: (impl(ghc >= 8.10.1)) && (impl(ghc < 8.11.0))
      source-dirs: app-ghc-8.10

    - condition: (impl(ghc >= 9.6.1)) && (impl(ghc < 9.7.0))
      source-dirs: app-ghc-9.6

    - condition: (impl(ghc >= 9.8.1)) && (impl(ghc < 9.9.0))
      source-dirs: app-ghc-9.8

    - condition: (impl(ghc >= 9.10.1)) && (impl(ghc < 9.11.0))
      source-dirs: app-ghc-9.10

    - condition: (impl(ghc >= 9.12.1)) && (impl(ghc < 9.13.0))
      source-dirs: app-ghc-9.12

    - condition: (impl(ghc >= 9.14.1)) && (impl(ghc < 9.15.0))
      source-dirs: app-ghc-9.14

    - condition: os(windows)
      then:
        dependencies:
        - Win32
      else:
        dependencies:
        - unix
